/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#005227',
        'primary':                   '#ffb2be',
        'surface-container-low':     '#1c1b1b',
        'primary-fixed':             '#ffd9de',
        'inverse-on-surface':        '#313030',
        'on-error':                  '#690005',
        'surface':                   '#131313',
        'inverse-primary':           '#bc004b',
        'error-container':           '#93000a',
        'surface-container-highest': '#353534',
        'on-secondary-fixed-variant':'#474746',
        'tertiary':                  '#6ddd8e',
        'outline-variant':           '#5b3f43',
        'on-surface-variant':        '#e4bdc2',
        'secondary-fixed-dim':       '#c8c6c5',
        'background':                '#131313',
        'on-surface':                '#e5e2e1',
        'surface-container-high':    '#2a2a2a',
        'on-tertiary-fixed':         '#00210c',
        'primary-container':         '#ff4e7c',
        'tertiary-fixed':            '#89faa8',
        'on-secondary':              '#313030',
        'on-tertiary':               '#003919',
        'surface-bright':            '#3a3939',
        'on-secondary-fixed':        '#1c1b1b',
        'surface-container-lowest':  '#0e0e0e',
        'on-error-container':        '#ffdad6',
        'error':                     '#ffb4ab',
        'secondary-container':       '#474746',
        'on-primary-container':      '#5a0020',
        'on-tertiary-container':     '#003115',
        'surface-dim':               '#131313',
        'primary-fixed-dim':         '#ffb2be',
        'outline':                   '#ab888c',
        'inverse-surface':           '#e5e2e1',
        'tertiary-container':        '#30a45c',
        'tertiary-fixed-dim':        '#6ddd8e',
        'on-background':             '#e5e2e1',
        'on-primary-fixed':          '#400014',
        'secondary':                 '#c8c6c5',
        'on-primary':                '#660025',
        'surface-tint':              '#ffb2be',
        'secondary-fixed':           '#e5e2e1',
        'on-secondary-container':    '#b7b5b4',
        'surface-container':         '#201f1f',
        'on-primary-fixed-variant':  '#900038',
        'surface-variant':           '#353534',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        'gutter':                   '24px',
        'section-padding-desktop':  '120px',
        'unit':                     '8px',
        'section-padding-mobile':   '64px',
        'container-max-width':      '1280px',
      },
      fontFamily: {
        'display-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md':           ['Inter', 'sans-serif'],
        'headline-md':       ['Plus Jakarta Sans', 'sans-serif'],
        'label-mono':        ['JetBrains Mono', 'monospace'],
        'body-lg':           ['Inter', 'sans-serif'],
        'display-lg':        ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg-mobile': ['40px',  { lineHeight: '1.2', fontWeight: '700' }],
        'body-md':           ['16px',  { lineHeight: '1.5', fontWeight: '400' }],
        'headline-md':       ['36px',  { lineHeight: '1.3', fontWeight: '600' }],
        'label-mono':        ['14px',  { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg':           ['18px',  { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg':        ['72px',  { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max-width': '1280px',
      },
    },
  },
  plugins: [],
}
